### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
Thanks for taking care of the module! :slightly_smiling_face:  I've also reviewed your fork  and have some change suggestions.

- Update workflows.
- Update devDependencies.
- Update lint process.
- Lint and format files.

There are no functional changes, but linter and formatter help to ensure code quality.

### CODE REVIEW

**Comment by parnic** [comment]
I really don't care how it's formatted, lol. Fix the build and I'll merge, I guess. Not sure I understand the value if nothing is improving or changing, but it's fine.

**Comment by KristjanESPERANTO** [comment]
Sorry, I've to figure out why the tests are failing. When I run the test locally there are without errors.

**Comment by KristjanESPERANTO** [comment]
Regarding the value of linter and formatter: They help maintain code consistency and catch potential issues early, which can save time and reduce bugs in the long run. This is especially important in open source projects where developers with varying skill levels contribute to the codebase :slightly_smiling_face:

**Comment by parnic** [comment]
> Regarding the value of linter and formatter: They help maintain code consistency and catch potential issues early, which can save time and reduce bugs in the long run. This is especially important in open source projects where developers with varying skill levels contribute to the codebase :slightly_smiling_face: 

Sure, I agree, but it was already linted and formatted, just not this way.

**Comment by KristjanESPERANTO** [comment]
Thanks for merging! :smiley: 

> Sure, I agree, but it was already linted and formatted, just not this way.

Ah, I didn't get your point right at first. This was caused by the upgrade of ESLint from **v7** to **v9** and switching to other ESLint plugins. We could have bent the rules more to fit the code, but I thought the changes were fine and not worth the effort.

**Pull request merged**
